### PR TITLE
fix(bug): don't print enum declarations as properties

### LINKED ISSUE #43: Provided enum static emit
browserevent.js
```
goog.provide('goog.events.BrowserEvent');
goog.provide('goog.events.BrowserEvent.MouseButton');
/**
 * @constructor
 * @extends {goog.events.Event}
 */
goog.events.BrowserEvent = function(opt_e, opt_currentTarget) {
}
/**
 * Normalized button constants for the mouse.
 * @enum {number}
 */
goog.events.BrowserEvent.MouseButton = {
  LEFT: 0,
  MIDDLE: 1,
  RIGHT: 2
};
```

we emit
```
  class BrowserEvent extends Event {
    isButton (a : BrowserEvent.MouseButton ) : boolean ;
    static MouseButton : BrowserEvent.MouseButton ;
  }
```

should be something like (if valid)

```
declare namespace goog.events {
class BrowserEvent {
  isButton (a: goog.events.BrowserEvent.MouseButton) {
}

declare namespace goog.events.BrowserEvent {
enum MouseButton {
 }
}
```

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #43

### CODE REVIEW

File: src/test/java/com/google/javascript/cl2dts/static_provided.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+/**
+ * Normalized button constants for the mouse.
+ * @enum {number}
+ */
+goog.events.BrowserEvent.MouseButton = {
+  LEFT: 0,
+  MIDDLE: 1,
+  RIGHT: 2
+};
```
Comment (rkirov) [inline src/test/java/com/google/javascript/cl2dts/static_provided.js]: Since the test is called static_provided, what about adding a static function that is also provided (I think it should just work).

Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/static_provided.js]: Nope actually adding that exposes another bug. We get a duplicate def'n of
the static method, inside the class as well as a namespace matching the
class name. Needs more work.

Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/static_provided.js]: Reworked a bit, now doing the Right Thing - PTAL

Comment (rkirov) [inline src/test/java/com/google/javascript/cl2dts/static_provided.js]: nice. still LGTM.

File: src/test/java/com/google/javascript/cl2dts/static_provided.d.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
+declare namespace ಠ_ಠ.cl2dts_internal.goog.events.BrowserEvent {
```
Comment (mprobst) [inline src/test/java/com/google/javascript/cl2dts/static_provided.d.ts]: Same comment as in other CL: in the interest of future understandability, please consider making the names/types explain what the tested use case it, not just C&P from Closure library.

Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/static_provided.d.ts]: done
