### PR TITLE
fix(bug): handle untyped object

### LINKED ISSUE #66: @const with no other type info
```
* @const
 * @private
 */
goog.userAgent.isVersionOrHigherCache_ = {};
```
emits a literal null (or fails with NPE with error-checking)

### PR DESCRIPTION
**Pull request by alexeagle**
fixes #66

### CODE REVIEW

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 1]
```diff
@@ -490,8 +490,10 @@ public Void caseStringType() {
         public Void caseObjectType(ObjectType type) {
           if (type.isRecordType()) {
             visitRecordType((RecordType) type);
-          } else {
+          } else if (type.getReferenceName() != null) {
             emit(type.getReferenceName());
+          } else {
+            emit("Object");
```
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: I think we need 'any' as the fallback. `Object` is very restrictive.

File: src/test/java/com/google/javascript/cl2dts/types.js [hunk 2]
```diff
@@ -59,3 +59,13 @@ types.j = {a: 'a'};
  * @template K,V
  */
 types.objectWithGenericKeyType = function(obj) { };
+
+/**
+ * @const
```
Comment (rkirov) [inline src/test/java/com/google/javascript/cl2dts/types.js]: is const needed for type inference?

Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/types.js]: Without const, the symbol doesn't appear in the topScope (I assume because it gets removed because it's unused). @export would work just as well

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 1 above)
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: We are inside of caseObjectType here, so I don't think it's necessary to widen to `any`. Maybe there's a test case I'm missing though

File: src/test/java/com/google/javascript/cl2dts/types.js (hunk 2 above)
Comment (mprobst) [inline src/test/java/com/google/javascript/cl2dts/types.js]: Maybe add a comment explaining that, or at least documenting that this was necessary?

Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/types.js]: Well, then I don't understand this very well. I tried `@export` and that _doesn't_ appear in `compiler.getTopScope().getAllSymbols()` but I don't know why.
For now, I've added the comment explaining why `@const` is here.

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 1 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: true.

File: src/test/java/com/google/javascript/cl2dts/types.js (hunk 2 above)
Comment (rkirov) [inline src/test/java/com/google/javascript/cl2dts/types.js]: ah, the mysteries of closure. Good enough for now.
