### PR TITLE
fix(interface): statics on interfaces emitted in a namespace.

### LINKED ISSUE #78: duplicate output for interface with nested enum
see goog.fx.Transition (interface) and goog.fx.Transition.EventType (enum).

Output is 
```javascript
declare namespace ಠ_ಠ.cl2dts_internal.goog.fx {                                                      
  interface Transition {                                                                             
    play : any ;                                                                                     
    stop : any ;                                                                                     
  }                                                                                                  
  var Transition : { EventType : Transition.EventType }                                              
}  

declare namespace ಠ_ಠ.cl2dts_internal.goog.fx.Transition {...}
```

I think it is safe to assume that nested classes, enums, and interfaces will have their own goog.provide and plainly skip them from the properties of the parent classes, enums, interfaces.

In this case Transition.EventType is provided explicitly.

### PR DESCRIPTION
**Pull request by rkirov**
We emit the static methods and variable in a namespace, instead of a var
union type, as done previously. That way we do not interfere with any
enums being output.

Closes #78

### CODE REVIEW

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 1]
```diff
@@ -287,11 +280,39 @@ private void declareNamespace(String namespace, TypedVar symbol, boolean isDefau
         }
       }
     }
+    emitNamespaceEnd();
+    // An extra pass is required for default exported interfaces, because in Closure they might have
+    // static methods. TS does not support static methods on interfaces, thus we create a new namespace for them.
+    if (isDefault && isInterfaceWithStatic(symbol.getType())) {
+      emitNamespaceBegin(symbol.getName ());
```
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: nit: extra space

File: src/test/java/com/google/javascript/cl2dts/interface.js [hunk 2]
```diff
@@ -11,3 +12,9 @@ interface_exp.staticMethod = function() {return interface_exp.staticProp;};
 
 /** @type {number} */
 interface_exp.staticProp = 0;
+
+/** @enum {number} */
+interface_exp.SomeEnum = {
+  A: 1,
+  B: 2
+};
```
Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/interface.js]: trailing newline

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 3]
```diff
@@ -287,11 +280,39 @@ private void declareNamespace(String namespace, TypedVar symbol, boolean isDefau
...
+      treeWalker.walkDefaultInterface((FunctionType) symbol.getType());
+      emitNamespaceEnd();
+    }
+  }
+
+  private boolean isInterfaceWithStatic(JSType type) {
```
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: opt: relocate the method near the other predicates?

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 4]
```diff
@@ -287,11 +280,39 @@ private void declareNamespace(String namespace, TypedVar symbol, boolean isDefau
...
+    return any(ftype.getOwnPropertyNames(), not(equalTo("prototype")));
+  }
+
+  private void emitNamespaceEnd() {
     unindent();
     emit("}");
     emitBreak();
   }
 
+  private void emitNamespaceBegin(String namespace) {
```
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: begin before end

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 5]
```diff
@@ -499,6 +507,21 @@ private void walk(TypedVar symbol, boolean isDefault) {
...
+    private void walkDefaultInterface(FunctionType ftype) {
+      for (String propName : ftype.getOwnPropertyNames()) {
+        if (propName.equals("prototype")) continue;
+        JSType pType = ftype.getPropertyType(propName);
+        // Here we assume the enum is exported and handled separately.
+        if (pType.isEnumType()) continue;
+        emit("var");
+        emit(propName);
+        emit(":");
+        visitType(pType);
```
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: this was visitRecordLikeType before - changed intentionally?

**Comment by alexeagle** [comment]
LGTM

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 5 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Yes, the output goes from `var recordLike = {foo: A, bar: B}` to 
```
namespace NamespaceLike {
  var foo: A;
  var bar: B;
}
```

I am also removing visitRecordLike since it is not needed any longer. `walkDefaultInterface` can become `visitNamespaceLike` in case we find more usage for it.
