### PR TITLE
fix(types): emit object types

### LINKED ISSUE #54: Type 'Object' is not generic
We are writing eg `  var VOID_TAGS_ : Object < string , boolean > ;`
but this is not valid TS.

Could be `var VOID_TAGS_ : { [s: string]: string; };` instead

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #54

### CODE REVIEW

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 1]
```diff
@@ -2,15 +2,15 @@
 
 import static com.google.common.base.Preconditions.checkArgument;
 import static com.google.common.base.Preconditions.checkState;
+import static com.google.common.base.Predicates.equalTo;
```
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: already added those in my commit, rebase.

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 2]
```diff
@@ -513,10 +513,28 @@ public Void caseTemplatizedType(TemplatizedType type) {
             emit("[]");
             return null;
           }
+          Iterator<JSType> it = type.getTemplateTypes().iterator();
+          if ("Object".equals(referencedType.getReferenceName())) {
+            emit("{ [");
+            // TS allows only number or string as index type of an object
+            // https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.9.4
+            if (it.next().isNumberValueType()) {
+              emit("n: number");
```
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: And the runtime only allows strings as keys, so all that is damn lies :)

check
```
a = {};a[0] = 1; a['0']
```

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 3]
```diff
@@ -513,10 +513,28 @@ public Void caseTemplatizedType(TemplatizedType type) {
...
+            } else {
+              emit("s: string");
+            }
```
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: should we warn if the input was anything outside `string|number`, so users are not surprised?

File: src/test/java/com/google/javascript/cl2dts/types.js [hunk 4]
```diff
@@ -50,3 +50,23 @@ types.h = {a: 'a', b: 34};
...
+/**
+ * Whether the object/map/hash contains the given value. This is O(n).
+ *
+ * @param {Object<K,V>} obj The object in which to look for val.
+ * @param {V} val The value for which to check.
+ * @return {boolean} true If the map contains the value.
+ * @template K,V
+ */
+types.containsValue = function(obj, val) {
+    for (var key in obj) {
```
Comment (rkirov) [inline src/test/java/com/google/javascript/cl2dts/types.js]: why include all that junk, we just need `@param {Object<K,V>}`.

**Comment by rkirov** [comment]
LGTM.

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 2 above)
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Maybe so, but I think this is correct according to spec?

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 3 above)
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Yes, but I don't think we have any channel through Bazel to report those warnings somewhere the user can see. Maybe we could emit a comment into the .d.ts saying what happened here?

Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: added a warning in an inline comment, tell me what you think

File: src/test/java/com/google/javascript/cl2dts/types.js (hunk 4 above)
Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/types.js]: done

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 3 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: good workaround for now.

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 2 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: yes, it was just an observation, matching the TS spec is the right thing for us.

**Comment by rkirov** [comment]
still LGTM.

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 5]
```diff
@@ -513,10 +513,32 @@ public Void caseTemplatizedType(TemplatizedType type) {
             emit("[]");
             return null;
           }
+          Iterator<JSType> it = type.getTemplateTypes().iterator();
+          if ("Object".equals(referencedType.getReferenceName())) {
```
Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: I think somewhere in the type registry there is a specific constant (marker? something?) that identifies the one, special `Object` type. Maybe you could use that?

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 6]
```diff
@@ -513,10 +513,32 @@ public Void caseTemplatizedType(TemplatizedType type) {
...
+            emit("{ [");
```
Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: If the type is not templatized, could we just emit `Object`? Always emitting `{ [key: string]: number }` is a bit misleading - there are usages that are intended to be used as pseudo-maps (`Object<string, SomeThing>`) and usages where `Object` is just the super type of everything (well, most things). I think the latter should be translated as just `Object`, so that TypeScript doesn't offer arbitrary indexing into it.

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 7]
```diff
@@ -513,10 +513,32 @@ public Void caseTemplatizedType(TemplatizedType type) {
...
+            // TS allows only number or string as index type of an object
+            // https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.9.4
+            JSType keyType = it.next();
+            if (keyType.isNumberValueType()) {
+              emit("n: number");
+            } else {
+              if (!keyType.isStringValueType()) {
+                emit("/* warning: coerced from " + keyType + "*/");
```
Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Could we print out a warning to the console?

Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Nit: add a trailing space in `"*/*"`?

File: src/test/java/com/google/javascript/cl2dts/types.js [hunk 8]
```diff
@@ -50,3 +50,12 @@ types.h = {a: 'a', b: 34};
...
 types.identity = function(a) { return a; };
+
+/** @type {Object<number, string>} */
+types.j = {a: 'a'};
+
+/**
+ * @param {Object<K,V>} obj The object in which to look for val.
+ * @template K,V
+ */
+types.containsValue = function(obj) { };
```
Comment (mprobst) [inline src/test/java/com/google/javascript/cl2dts/types.js]: Nit: in general, I think it'd be nicer to have tests that express some concept, instead of just being C&P from the Closure library. It'll make it easier to understand this tests in the future. E.g. here: `types.objectWithGenericKeyType` or so?

File: src/test/java/com/google/javascript/cl2dts/types.js [hunk 9]
```diff
@@ -50,3 +50,12 @@ types.h = {a: 'a', b: 34};
  * @template T
  */
 types.identity = function(a) { return a; };
+
+/** @type {Object<number, string>} */
+types.j = {a: 'a'};
+
+/**
+ * @param {Object<K,V>} obj The object in which to look for val.
```
Comment (mprobst) [inline src/test/java/com/google/javascript/cl2dts/types.js]: This comment is a bit of a distraction, isn't it?

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 5 above)
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: indeed, `typeRegistry.getNativeType(JSTypeNative.OBJECT_TYPE)`, fixed here and for Array above

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java (hunk 6 above)
Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: we have a test for that already in the `types.js`:
```
/** @type {Object} */
types.d = {};
```

Note this code is in `caseTemplatizedType`

File: src/test/java/com/google/javascript/cl2dts/types.js (hunk 8 above)
Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/types.js]: yeah, I've been in a hurry here trying to get a demo working. agree these names would be good documentation

File: src/test/java/com/google/javascript/cl2dts/types.js (hunk 9 above)
Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/types.js]: done
