### PR TITLE
fix(generics): output templatized types for extends.

### LINKED ISSUE #89: Generics in implemented interfaces are not output
The following:

```javascript

 * @implements {goog.Thenable<TYPE>}
 * @template TYPE,RESOLVER_CONTEXT
 */
goog.Promise = function(resolver, opt_context) {...}
```

outputs 

```typescript
class Promise < TYPE , RESOLVER_CONTEXT > implements Thenable {
```

But it should be ```Thenable<TYPE>```.

### PR DESCRIPTION
**Pull request by rkirov**
Closes #89

### CODE REVIEW

File: src/test/java/com/google/javascript/cl2dts/generics_usage.ts [hunk 1]
```diff
@@ -8,3 +8,7 @@ f.loop<number, number>("thing", 123);
 f = fooMissingAllTypeParams;
 
 class Test implements ExtendGenericInterface<string> {}
+
+var i: GenericInterface<string> = new ImplementsGenericInterface<string>();
+
+var i2: GenericInterface<string> = new ExtendsGenericClass<string>();
```
Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/generics_usage.ts]: no newline

File: src/test/java/com/google/javascript/cl2dts/generics.js [hunk 2]
```diff
@@ -62,3 +62,18 @@ generics.GenericInterface = function() {};
...
+ * @implements {generics.GenericInterface<TYPE>}
+ */
+generics.ImplementsGenericInterface = function() {}
+
+/**
+ * @constructor
+ * @template TYPE
+ * @extends {generics.Foo<TYPE, number>}
+ */
+generics.ExtendsGenericClass = function() {}
```
Comment (alexeagle) [inline src/test/java/com/google/javascript/cl2dts/generics.js]: newline

**Comment by alexeagle** [comment]
very nice, LGTM
