### PR TITLE
fix(bug): allow nullable parameterized types

### LINKED ISSUE #56: generic type param missing from signature
```
* @param {function(this:SCOPE)|{handleEvent:function()}|null} listener Function
 *     or object that has a handleEvent method.
 * @param {number=} opt_delay Milliseconds to wait; default is 0.
 * @param {SCOPE=} opt_handler Object in whose scope to call the listener.
 * @return {number} A handle to the timer ID.
 * @template SCOPE
 */
goog.Timer.callOnce = function(listener, opt_delay, opt_handler) {
```
```
static callOnce < SCOPE > (listener : ( ( ) => any | { handleEvent : ( ) => any } ) , opt_delay ? : number , opt_handler ? : ( ) ) : number ;
```

the type of opt_handler is `( )` which is not valid

### PR DESCRIPTION
**Pull request by alexeagle**
fixes #56

### CODE REVIEW

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 1]
```diff
@@ -629,7 +629,9 @@ private void visitUnionType(UnionType ut) {
         public boolean apply(JSType input) {
           // Skip - TypeScript does not have explicit null or optional types.
           // Optional types must be handled at the declaration name (`foo?` syntax).
-          return !input.isNullable() && !input.isVoidType();
+          return !input.isNullable() && !input.isVoidType()
```
Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Could you add parenthesis so this doesn't rely on operator precedence?

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 2]
```diff
@@ -629,7 +629,9 @@ private void visitUnionType(UnionType ut) {
...
+              // Template types are always nullable, but we should not skip them
+              || input.isTemplateType();
```
Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: The intention of the code was that unions commonly contain `Foo|null`, and we'd like to filter out the `null` case. Maybe the Real Bug is that this should not be `!input.isNullable()` but rather `!input.isSpecialNullType()` (I'm making that up)? I.e. the difference between the type permitting/including `null`, and the type actually being the special `null` type?

Comment (alexeagle) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Yup, just isNullType() looks pretty good to me.
