### PR TITLE
fix(bug): check for name == namespace

### LINKED ISSUE #86: Index out of bounds
```
Caused by: java.lang.RuntimeException: Failed to emit type goog.ui.ac.Renderer
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.visitType(DeclarationGenerator.java:725)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.visitUnionType(DeclarationGenerator.java:773)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.access$1100(DeclarationGenerator.java:388)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker$1.caseUnionType(DeclarationGenerator.java:606)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker$1.caseUnionType(DeclarationGenerator.java:566)
	at com.google.javascript.rhino.jstype.UnionType.visit(UnionType.java:601)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.visitType(DeclarationGenerator.java:723)
	... 24 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1918)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.getRelativeName(DeclarationGenerator.java:401)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.access$1000(DeclarationGenerator.java:388)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker$1.caseObjectType(DeclarationGenerator.java:597)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker$1.caseObjectType(DeclarationGenerator.java:566)
	at com.google.javascript.rhino.jstype.ObjectType.visit(ObjectType.java:524)
	at com.google.javascript.cl2dts.DeclarationGenerator$TreeWalker.visitType(DeclarationGenerator.java:723)

```

### PR DESCRIPTION
**Pull request by alexeagle**
also cleanup a duplicated test case
fixes #86

### CODE REVIEW

File: src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java [hunk 1]
```diff
@@ -398,6 +398,7 @@ private TreeWalker(String namespace, JSTypeRegistry typeRegistry, Set<String> pr
 
     private String getRelativeName(ObjectType objectType) {
       String name = objectType.getDisplayName();
+      if (name.equals(namespace)) return name;
```
Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: braces! (Google Style)

Comment (mprobst) [inline src/main/java/com/google/javascript/cl2dts/DeclarationGenerator.java]: Or actually not, I like this style better anyway.
